# 'true' will fix files
autofix: true

# list of paths to ignore, uses gitignore syntaxes (executes before any rule)
ignore:
  - .git/
  - .gradle/
  - src/test/resources/restapi/users_key_not_quoted.json

rules:
  # checks if file ends in a newline character
  end-of-file:
    # set to true to enable this rule
    enable: true

    # if true also checks if file ends in a single newline character
    single-new-line: true
