coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
      # Exclusions to prevent false positives triggered
      # Tracking with https://github.com/opensearch-project/security/issues/3137
      inconsistant-coverage-files:
        paths:
          - "src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/SelfRefreshingKeySet.java"
          - "src/main/java/com/amazon/dlic/auth/ldap2/LDAPConnectionFactoryFactory.java"
          - "src/main/java/org/opensearch/security/transport/SecurityInterceptor.java"
          - "src/main/java/org/opensearch/security/auditlog/AuditLogSslExceptionHandler.java"
          - "src/main/java/org/opensearch/security/configuration/StaticResourceException.java"
          - "src/main/java/org/opensearch/security/dlic/rest/api/AuditApiAction.java"
          - "src/main/java/org/opensearch/security/ssl/transport/SecuritySSLNettyTransport.java"
          - "src/main/java/org/opensearch/security/ssl/util/SSLConnectionTestUtil.java"
        target: auto
        threshold: 50%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
