---
_meta:
  type: "whitelisting_settings"
  config_version: 2

#if whitelisting_enabled is false, the whitelisting feature is removed.
#this is equivalent to whitelisting all APIs, and continuing with the usual access control checks
#if whitelisting_enabled is true, then all users except SuperAdmin can access only the APIs in whitelistedAPIs
#SuperAdmin can access all APIs.
#SuperAdmin is defined by the SuperAdmin certificate, which is configured in the elasticsearch.yml setting: opendistro_security.authcz.admin_dn:
#Refer to the example setting in elasticsearch.yml.example, and the opendistro documentation to know more about configuring SuperAdmin.

#this name must be whitelisting_settings
whitelisting_settings:
  whitelisting_enabled: false
  whitelisted_APIs: ["/_cat/nodes", "/_cat/plugins", "/_cluster/health", "/_cluster/settings"]

