name: 'Create a backwards compatible ready build'
description: 'Checkouts the official version of a the Security plugin and builds it so it can be used for BWC tests'

inputs:
  plugin-branch:
    description: 'The branch of the plugin that should be built, e.g "2.2", "1.x"'
    required: true

outputs:
  built-version:
    description: 'The version of OpenSearch that was associated with this branch'
    value: ${{ steps.get-opensearch-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Enable Longpaths if on Windows
      if: ${{ runner.os == 'Windows' }}
      run: git config --system core.longpaths true
      shell: pwsh

    - name: Checkout Branch from Fork
      if: ${{ inputs.plugin-branch == 'current_branch' }}
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        path: ${{ inputs.plugin-branch }}

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      if: ${{ inputs.plugin-branch != 'current_branch' }}
      with:
        repository: opensearch-project/security
        ref: ${{ inputs.plugin-branch }}
        path: ${{ inputs.plugin-branch }}

    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      if: ${{ inputs.plugin-branch == 'current_branch' }}
      with:
        distribution: temurin # Temurin is a distribution of adoptium
        java-version: 21

    - name: Build
      uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
      with:
        cache-disabled: true
        arguments: assemble
        build-root-directory: ${{ inputs.plugin-branch }}

    - id: get-opensearch-version
      run: |
        echo "version=$(./gradlew properties -Dbuild.snapshot=false | grep ^version: | awk '{split($0, a, ": ");print a[2]}')" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.plugin-branch }}
      shell: bash

    - name: Copy current distro into the expected folder
      run: |
        mkdir -p ./bwc-test/src/test/resources/${{ steps.get-opensearch-version.outputs.version }}
        cp ${{ inputs.plugin-branch }}/build/distributions/opensearch-security-${{ steps.get-opensearch-version.outputs.version }}-SNAPSHOT.zip ./bwc-test/src/test/resources/${{ steps.get-opensearch-version.outputs.version }}
      shell: bash
