services:
  opensearch-node1:
    image: opensearchstaging/opensearch:3.8.0
    container_name: corr-test-node1
    environment:
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Admin!2026
    volumes:
      - ./plugin:/usr/share/opensearch/plugins/opensearch-security
      - ./opensearch-node1.yml:/usr/share/opensearch/config/opensearch.yml
      - ./certs:/usr/share/opensearch/config/certs
    ports:
      - "9200:9200"
    networks:
      - corr-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
  opensearch-node2:
    image: opensearchstaging/opensearch:3.8.0
    container_name: corr-test-node2
    environment:
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Admin!2026
    volumes:
      - ./plugin:/usr/share/opensearch/plugins/opensearch-security
      - ./opensearch-node2.yml:/usr/share/opensearch/config/opensearch.yml
      - ./certs:/usr/share/opensearch/config/certs
    networks:
      - corr-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
networks:
  corr-net:
