cluster.name: corr-test
node.name: node-1
network.host: 0.0.0.0
discovery.seed_hosts: ["opensearch-node2"]
cluster.initial_cluster_manager_nodes: ["node-1"]

# TLS
plugins.security.ssl.transport.pemcert_filepath: certs/node.pem
plugins.security.ssl.transport.pemkey_filepath: certs/node-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: certs/root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: certs/node.pem
plugins.security.ssl.http.pemkey_filepath: certs/node-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: certs/root-ca.pem

# FGAC security
plugins.security.allow_default_init_securityindex: true
plugins.security.allow_unsafe_democertificates: true
plugins.security.nodes_dn:
  - "CN=node-1"
plugins.security.authcz.admin_dn:
  - "CN=taiwo,OU=intern,O=amazon"
  - "O=amazon,OU=intern,CN=taiwo"

# Audit — log4j sink, all categories
plugins.security.audit.type: log4j
plugins.security.audit.config.log4j.logger_name: audit
plugins.security.audit.config.log4j.level: INFO
plugins.security.audit.config.log_request_body: true
plugins.security.audit.config.exclude_sensitive_headers: true
plugins.security.audit.config.resolve_indices: true
plugins.security.audit.config.resolve_bulk_requests: true
plugins.security.audit.config.enable_rest: true
plugins.security.audit.config.enable_transport: true
plugins.security.audit.config.disabled_rest_categories: []
plugins.security.audit.config.disabled_transport_categories: []

# Compliance
plugins.security.audit.compliance.enabled: true
opendistro_security.compliance.history.write.watched_indices: "corr-*"
opendistro_security.compliance.history.read.watched_fields: "corr-*"
opendistro_security.compliance.history.write.metadata_only: false
opendistro_security.compliance.history.read.metadata_only: false
opendistro_security.compliance.history.write.log_diffs: true
