name: automatic-merges

on:
  workflow_run:
    workflows:
      - CI
      - Plugin Install
      - Code Hygiene
    types: completed

jobs:
  automatic-merge-version-bumps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: 22958780

      - id: find-triggering-pr
        uses: peternied/find-triggering-pr@ebe6a5ff5d5edfdf31b1f8aca20f89167c57bbef # v1
        with:
          token: ${{ steps.github_app_token.outputs.token }}

      - uses: peternied/discerning-merger@07eafb14c195a2c23b291f6b008a686589cfb545 # v3
        if: steps.find-triggering-pr.outputs.pr-number != null
        with:
          token: ${{ steps.github_app_token.outputs.token }}
          pull-request-number: ${{ steps.find-triggering-pr.outputs.pr-number }}
          allowed-authors: |
            dependabot[bot]
            opensearch-trigger-bot[bot]
          allowed-files: |
            build.gradle
            CHANGELOG.md
            .github/workflows/*.yml
