name: automatic-merges

on:
  workflow_run:
    workflows:
      - CI
      - Plugin Install
      - Code Hygiene
    types: completed

jobs:
  automatic-merge-version-bumps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: GitHub App token
        id: github_app_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: find-triggering-pr
        uses: peternied/find-triggering-pr@ebe6a5ff5d5edfdf31b1f8aca20f89167c57bbef # v1
        with:
          token: ${{ steps.github_app_token.outputs.token }}

      - uses: peternied/discerning-merger@07eafb14c195a2c23b291f6b008a686589cfb545 # v3
        if: steps.find-triggering-pr.outputs.pr-number != null
        with:
          token: ${{ steps.github_app_token.outputs.token }}
          pull-request-number: ${{ steps.find-triggering-pr.outputs.pr-number }}
          allowed-authors: |
            dependabot[bot]
            opensearch-trigger-bot[bot]
          allowed-files: |
            build.gradle
            CHANGELOG.md
            .github/workflows/*.yml
