name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Backport
    steps:
      - name: Backport
        uses: VachaShah/backport@v1.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_name: backport/backport-${{ github.event.number }}
