name: Code Hygiene

on: [push, pull_request]

jobs:
  linelint:
    runs-on: ubuntu-latest
    name: Check if all files end in newline
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Linelint
        uses: fernandrone/linelint@7907a5dca0c28ea7dd05c6d8d8cacded713aca11 # 0.0.6

  spotless:
    runs-on: ubuntu-latest
    name: Spotless scan
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: 21

      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-disabled: true

      - run: ./gradlew spotlessCheck

  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle scan
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: 21

      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-disabled: true

      - run: ./gradlew checkstyleMain checkstyleTest checkstyleIntegrationTest

  spotbugs:
    runs-on: ubuntu-latest
    name: Spotbugs scan
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: 21

      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-disabled: true

      - run: ./gradlew spotbugsMain

  check-permissions-order:
    runs-on: ubuntu-latest
    name: Check permissions orders
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
    - run: npm install yaml

    - name: Check permissions order
      run: |
        exclude_pattern="(^|/)roles_invalidxcontent.yml($|/)
                          (^|/)invalid_config/config.yml($|/)"
        # Set pattern to exclude certain files
        set -e
        exit_code=0
        for file in $(find . -name '*.yml' | grep -Ev "$exclude_pattern"); do
          if ! node check-permissions-order.js "$file" --slient; then
            exit_code=1
            echo "Error: $file requires changes. Run the following command to fix:"
            echo "node check-permissions-order.js $file --fix"
          fi
        done
        exit $exit_code
