name: Bulk Integration Test

on: [workflow_dispatch]

env:
  GRADLE_OPTS: -Dhttp.keepAlive=false

jobs:
  bulk-integration-test-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: [21, 25]
        test-run: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
    - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:
        distribution: temurin # Temurin is a distribution of adoptium
        java-version: ${{ matrix.jdk }}

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

    - run: ./gradlew test

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      if: always()
      with:
        name: ${{ matrix.jdk }}-${{ matrix.test-run }}-reports
        path: |
          ./build/reports/

    - name: check archive for debugging
      if: always()
      run: echo "Check the artifact ${{ matrix.jdk }}-${{ matrix.test-run }}-reports.zip for detailed test results"
