---
name: License Header Checker

on: [push, pull_request]

jobs:
  license-header-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - name: Check License Headers
        run: npx --yes @kt3k/license-checker@3.2.2
