name: Link Checker
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@6da1d14f3a43098a294b7696d93d938aa8d20fc0 # master
        with:
          args: --accept=200,403,429  **/*.html **/*.md **/*.txt **/*.json --exclude-path src/test/resources/dlsfls/logs_bulk_data.json
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
