name: Plugin Install

on: [push, pull_request, workflow_dispatch]

env:
  OPENSEARCH_VERSION: 2.19.6
  PLUGIN_NAME: opensearch-security

jobs:
  plugin-install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk: [11, 17, 21]
    runs-on: ${{ matrix.os }}

    steps:
      - id: random-password
        uses: peternied/random-name@71fad5c68f7d02fcfa756b09d8d6368731fa0c37 # v1

      - name: Set up JDK
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: ${{ matrix.jdk }}

      - name: Checkout Branch
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Assemble target plugin
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
        with:
          cache-disabled: true
          arguments: assemble

      # Move and rename the plugin for installation
      - name: Move and rename the plugin for installation
        run: mv ./build/distributions/${{ env.PLUGIN_NAME }}-*.zip ${{ env.PLUGIN_NAME }}.zip
        shell: bash

      - name: Run Opensearch with A Single Plugin
        uses: opensearch-project/opensearch-build/.github/actions/start-opensearch@58029ed0db12929e8e920eb875925335583f9490
        if: ${{ runner.os != 'Windows' }}
        with:
          opensearch-version: ${{ env.OPENSEARCH_VERSION }}
          plugins: "file:$(pwd)/${{ env.PLUGIN_NAME }}.zip"
          security-enabled: true
          admin-password: ${{ steps.random-password.outputs.generated_name }}
          jdk-version: 17

      - name: Run Opensearch with A Single Plugin
        uses: opensearch-project/opensearch-build/.github/actions/start-opensearch@58029ed0db12929e8e920eb875925335583f9490
        if: ${{ runner.os == 'Windows' }}
        with:
          opensearch-version: ${{ env.OPENSEARCH_VERSION }}
          plugins: "file:///$((Get-Location).Path -replace '\\\\','/')/${{ env.PLUGIN_NAME }}.zip"
          security-enabled: true
          admin-password: ${{ steps.random-password.outputs.generated_name }}
          jdk-version: 17

      - name: Run sanity tests
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
        with:
          cache-disabled: true
          arguments: integTestRemote -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="opensearch" -Dhttps=true -Duser=admin -Dpassword=${{ steps.random-password.outputs.generated_name }} -i
