name: Plugin Install

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  OPENSEARCH_VERSION: 3.8.0
  PLUGIN_NAME: opensearch-security

jobs:
  plugin-install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk: [21, 25]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Generate Strong Password
        id: generate-password
        uses: DarshitChanpura/secure-password-action@70c04529b3705c2f0f5fb81d26b29d11ce120d18 # v1.0.0

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: ${{ matrix.jdk }}

      - name: Checkout Branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Assemble target plugin
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
        with:
          cache-disabled: true
          arguments: assemble

      # Move and rename the plugin for installation
      - name: Move and rename the plugin for installation
        run: mv ./build/distributions/${{ env.PLUGIN_NAME }}-*.zip ${{ env.PLUGIN_NAME }}.zip
        shell: bash

      - name: Run Opensearch with A Single Plugin
        uses: opensearch-project/opensearch-build/.github/actions/start-opensearch@58029ed0db12929e8e920eb875925335583f9490
        if: ${{ runner.os != 'Windows' }}
        with:
          opensearch-version: ${{ env.OPENSEARCH_VERSION }}
          plugins: "file:$(pwd)/${{ env.PLUGIN_NAME }}.zip"
          security-enabled: true
          admin-password: ${{ steps.generate-password.outputs.password }}
          jdk-version: 21

      - name: Run Opensearch with A Single Plugin
        uses: opensearch-project/opensearch-build/.github/actions/start-opensearch@58029ed0db12929e8e920eb875925335583f9490
        if: ${{ runner.os == 'Windows' }}
        with:
          opensearch-version: ${{ env.OPENSEARCH_VERSION }}
          plugins: "file:///$((Get-Location).Path -replace '\\\\','/')/${{ env.PLUGIN_NAME }}.zip"
          security-enabled: true
          admin-password: ${{ steps.generate-password.outputs.password }}
          jdk-version: 21

      - name: Run sanity tests
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
        with:
          cache-disabled: true
          arguments: integTestRemote -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="opensearch" -Dhttps=true -Duser=admin -Dpassword=${{ steps.generate-password.outputs.password }} -i
