name: Release-drafter

on:
  push:
    branches: [main]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts the next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-notes-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
